# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('abstractpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.AbstractPost')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('author', models.CharField(max_length=255, verbose_name='Автор')),
                ('year', models.DateField(verbose_name='Время написания')),
                ('status', models.SmallIntegerField(choices=[(1, 'reading'), (2, 'have read'), (3, 'going to reread')])),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
            bases=('core.abstractpost',),
        ),
        migrations.CreateModel(
            name='BookPersonality',
            fields=[
                ('abstractpersonalitypost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.AbstractPersonalityPost')),
                ('books', models.ManyToManyField(related_name='personalities', to='books.Book')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
            bases=('core.abstractpersonalitypost',),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('abstractcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.AbstractCategory')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
            bases=('core.abstractcategory',),
        ),
        migrations.AddField(
            model_name='bookpersonality',
            name='genres',
            field=models.ManyToManyField(related_name='book_personalities', to='books.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(related_name='books', to='books.Genre'),
        ),
    ]
